apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-tenant-saas-api
  namespace: mt-saas
spec:
  template:
    metadata:
      annotations:
        app.kubernetes.io/version: REPLACE_WITH_GIT_SHA
    spec:
      containers:
        - name: api
          env:
            - name: APP_VERSION
              valueFrom:
                configMapKeyRef:
                  name: deployment-release
                  key: APP_VERSION
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
