apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mt-saas
resources:
  - ../../base
images:
  - name: multi-tenant-saas/api
    newName: REPLACE_WITH_ACR_LOGIN_SERVER/multi-tenant-saas/api
    newTag: REPLACE_WITH_GIT_SHA
configMapGenerator:
  - name: deployment-release
    literals:
      - APP_VERSION=REPLACE_WITH_GIT_SHA
    options:
      disableNameSuffixHash: true
replacements:
  - source:
      kind: ConfigMap
      name: deployment-release
      fieldPath: data.APP_VERSION
    targets:
      - select:
          kind: Deployment
          name: multi-tenant-saas-api
        fieldPaths:
          - spec.template.metadata.annotations.app\.kubernetes\.io/version
        options:
          create: true
patches:
  - path: namespace-exclusion-patch.yaml
  - path: deployment-patch.yaml
