apiVersion: v1
kind: Service
metadata:
  name: observability-backend
spec:
  type: ClusterIP
  selector:
    app: observability-backend
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
    - name: otlp-grpc
      port: 4317
      targetPort: otlp-grpc
      protocol: TCP
    - name: otlp-http
      port: 4318
      targetPort: otlp-http
      protocol: TCP
