apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mt-saas
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
images:
  - name: multi-tenant-saas/api
    newName: REPLACE_WITH_ACR_LOGIN_SERVER/multi-tenant-saas/api
    newTag: REPLACE_WITH_GIT_SHA
