apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mt-saas
resources:
  - namespace.yaml
  - service-account.yaml
  - configmap.yaml
  - resource-quota.yaml
  - limit-range.yaml
  - network-policy.yaml
  - deployment.yaml
  - service.yaml
  - ../observability
