apiVersion: v1
kind: ResourceQuota
metadata:
  name: mt-saas-workload-quota
  namespace: mt-saas
spec:
  hard:
    pods: "5"
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi
